/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <SDA.h>
#include <SDA_aliases.h>
#include <SCL.h>
#include <SCL_aliases.h>
#include <RST_1.h>
#include <RST_1_aliases.h>
#include <HMC5883L_I2C.h>
#include <HMC5883L_I2C_PVT.h>
#include <MISO.h>
#include <MISO_aliases.h>
#include <MOSI.h>
#include <MOSI_aliases.h>
#include <SCLK.h>
#include <SCLK_aliases.h>
#include <LIS331HH_SPI.h>
#include <LIS331HH_SPI_PVT.h>
#include <CS.h>
#include <CS_aliases.h>
#include <CONFIG_COM.h>
#include <DATA_COM.h>
#include <HMC5883L_I2C_IntClock.h>
#include <LIS331HH_SPI_IntClock.h>
#include <CONFIG_COM_IntClock.h>
#include <DATA_COM_IntClock.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

